[2.0] New: Implement lazy-imports
PolymerElements/polymer-starter-kit pull request #998
Opened 2017-04-07 02:24 UTC by stramel

2017-04-07 03:00 UTC, stramel commented on src/my-app.html
> +  <link rel="lazy-import" group="view1" href="src/my-view1.html">
I think I'm missing something in the `lazy-import`'s 2.0-preview in the `Polymer.ResoveUrl.resolveUrl` method with the `baseUri`

2017-04-07 03:01 UTC, stramel commented
Also, getting `HTMLImports.whenReady is not a function` error when it loads the lazy imports but it isn't blocking the imports.

2017-04-17 14:21 UTC, stramel commented
Pending decision in #997

2017-04-17 14:53 UTC, web-padawan commented on index.html
> +    <base href="/">
This would be a pain for those asking in Slack "how to serve PSK from a subfolder?"

2017-04-17 15:01 UTC, stramel commented on index.html
> +    <base href="/">
I can remove this. Not entirely sure why I added it, sorry!

2017-05-16 03:39 UTC, stramel commented
Looks like eslint is yelling at the capital on the mixin... thought it was correct.

2017-05-16 05:09 UTC, jsilvermist commented
Seems to me more of an eslint issue than a naming issue. After the rebase there are lazy imports both inside and outside of the dom-module, is this intentional? Also, what was the intention of the lazy imports outside the dom-module?

2017-05-16 05:23 UTC, stramel commented
@jsilvermist :scream: WUT... I don't even know... Fixing Now. Good catch!! Lazy-Imports should be in the dom-module.

I guess, wrt eslint, we should figure out how we want to go about this. I'm fully open to suggestions :)

2017-05-16 05:40 UTC, stramel commented
@jsilvermist I added a regex `Mixin$` for exceptions to the `newCap` rule. Again, open to suggestions!

2017-05-16 16:10 UTC, stramel commented
Rebased it, so it is a bit cleaner... 

@jsilvermist Seems like those other lazy-imports accidentally got in from @justinfagnani https://github.com/PolymerElements/polymer-starter-kit/commit/f037cfb00783a6cdd81d3728a8a0b1cee301f077

2017-05-16 16:17 UTC, stramel commented on .eslintrc.json
> +    "es6": true
`parserOptions` is set by this line.

http://eslint.org/docs/user-guide/configuring#specifying-environments

2017-05-16 18:13 UTC, abdonrd requested changes

2017-05-16 18:13 UTC, abdonrd commented on src/my-app.html
> +            if (results.failed.length > 0 || results.loaded.length < 1)
It is the best option?

cc @justinfagnani

2017-05-16 18:13 UTC, abdonrd commented on src/my-app.html
> +    class MyApp extends Polymer.LazyImportsMixin(Polymer.Element) {
We should add the annotations here?

```
/**
 * @extends Polymer.Element
 * @appliesMixin Polymer.LazyImportsMixin
 */
```

cc @rictic

2017-05-16 18:13 UTC, abdonrd commented on .eslintrc.json
> +    "new-cap": ["error", { "capIsNewExceptions": ["Polymer"], "capIsNewExceptionPattern": "Mixin$" }],
I think we can remove this rule.

2017-05-16 18:26 UTC, stramel commented on .eslintrc.json
> +    "new-cap": ["error", { "capIsNewExceptions": ["Polymer"], "capIsNewExceptionPattern": "Mixin$" }],
@abdonrd Removing this rule results in eslint error on `LazyImportsMixin`.

2017-05-16 18:27 UTC, stramel commented on src/my-app.html
> +    class MyApp extends Polymer.LazyImportsMixin(Polymer.Element) {
/sub

Curious about this 👍

2017-05-16 18:28 UTC, stramel commented on src/my-app.html
> +            if (results.failed.length > 0 || results.loaded.length < 1)
Not sure how else we would detect if a page has loaded or not to fall back to a 404 page.

2017-05-16 18:30 UTC, abdonrd commented on .eslintrc.json
> +    "new-cap": ["error", { "capIsNewExceptions": ["Polymer"], "capIsNewExceptionPattern": "Mixin$" }],
Oh, right, is enable by eslint-config-google!

2017-05-18 04:00 UTC, stramel commented on src/my-app.html
> +    class MyApp extends Polymer.LazyImportsMixin(Polymer.Element) {
Added some based off of this PR: https://github.com/Polymer/polymer/pull/4568/

2017-05-19 18:33 UTC, graynorton commented
Per the discussion in https://github.com/Polymer/polymer-cli/issues/748, I think we'll want to remove the explicit declaration of fragments in `polymer.json` as part of this change.

2017-05-19 19:35 UTC, stramel commented
@graynorton Removed them after discussion with @usergenic  and some initial testing, it appears that it will treat lazy-imports as implicit fragments since they are included in a fragment, the app-shell in this case.

2017-05-19 19:38 UTC, danizord commented on polymer.json
> +  "fragments": [],
I think you can remove this `fragments` key completely as seems like it is not usable anymore with lazy-imports.

2017-05-22 19:08 UTC, abdonrd commented on polymer.json
> +  "fragments": [],
I think the same.

2017-05-22 19:08 UTC, abdonrd commented on src/my-app.html
> +     */
We should add all these annotations?

cc @rictic @justinfagnani

2017-05-22 19:08 UTC, abdonrd commented on src/my-app.html
> +            if (results.failed.length > 0 || results.loaded.length < 1)
Can we get the list of the `lazy-imports` groups?

If we have an array of the groups names, we could avoid try to import a group that we already know does not exist.

2017-05-22 19:27 UTC, stramel commented on src/my-app.html
> +            if (results.failed.length > 0 || results.loaded.length < 1)
@abdonrd I suppose I could query the list of lazy-imports then check the group exists?

Seems like duplicate effort when if it doesn't find that group in the same query it just fails out by returning empty arrays for both failed and loaded.

2017-05-23 07:22 UTC, stramel commented
Rebased onto the latest of 2.0-preview

2017-05-28 14:32 UTC, abdonrd commented on src/my-app.html
> +            if (results.failed.length > 0 || results.loaded.length < 1)
I just saw how `Polymer.__importLazyGroup` works. You are right!

2017-05-28 14:53 UTC, stramel commented
So I think we are just waiting for @justinfagnani's review

2017-06-01 17:10 UTC, abdonrd commented on src/my-app.html
> +     */
Meanwhile, @stramel can you add the annotations to the other elements? To be consistent. Thanks in advance!

2017-06-01 18:05 UTC, rictic commented on src/my-app.html
> +     */
Yep, those annotations look correct to me. In the future we'd like to be able to infer as many of them as possible. e.g. we can probably already infer `@customElement` here because there's a `customElements.define` call for the element in this same file.

The simplest way to tell if the annotations are working is to look at the output of `polymer analyze`. @aomarks is actively working on the documentation viewer, but in the meantime you could just open the output in your favorite editor and grep around.

2017-06-01 18:25 UTC, stramel commented on src/my-app.html
> +     */
@abdonrd I have updated the annotations after discussing with @rictic.

`@customElement` and `@polymer` are inferred so I went ahead and dropped them.

2017-06-01 18:36 UTC, abdonrd commented on src/my-app.html
> +     */
Thanks to both!

2017-06-14 18:36 UTC, arthurevans commented
@justinfagnani hasn't weighed in, so I'm going to jump in and say we shouldn't merge this into PSK until we've done a good deal more groundwork to make sure lazy-imports are a thing.

Currently, lazy-imports aren't documented on the polymer site, or in the READMEs for polymer-cli or polymer-build. Even the lazy-imports README doesn't describe the benefits (https://github.com/Polymer/lazy-imports/issues/11). If we add them to the default starting point for new users without documenting them, it will confuse the heck out of new users. (Or even not-so-new users like me.)

As far as I can tell, this is sugar that lets you leave your fragments out of `polymer.json`, at the cost of an extra dependency. Is that an improvement on the current system? Have we profiled it to make sure it's not a regression compared to the current system?

I know @stramel has done a bunch of work on lazy-imports, I just think we should be purposeful about this change.

2017-06-14 19:52 UTC, stramel commented
@arthurevans First off I really appreciate your input and insight.

I definitely agree that it will need better documentation in general. I can work on adding that to the Polymer Docs and Tooling (CLI, Build, Bundler, Linter, etc) although I'm pretty bad at writing so I'm sure someone will have input on refining it. Hopefully @justinfagnani can clear up the benefits of `lazy-imports` in the README.

The largest benefit of it is that it offers a declarative way to handle a lazy dependency instead of the more programmatic way of handling it (`this.importHref('element.htm', null, null, true);`). This allows the tools to do better static analysis and provide a way to closer mimic html imports. The removal of `fragments` is a nice outcome of @usergenic's awesome work on the tools (Maybe @usergenic would like to weigh in as well).

WRT, profiling and improvement, I haven't actually looked into this too much. I'm not sure how to go about profiling but I can also try looking into that a bit more.

---

On another note, I feel like the fake lazy-imports that have been added to the PSK are going to really be confusing since they are not in the proper location and actually don't do anything other than prevent the linter from throwing warnings.

2017-06-14 21:04 UTC, arthurevans commented
Thanks @stramel. What are the fake lazy-imports? I haven't seen those.

2017-06-14 21:16 UTC, stramel commented
@arthurevans These are the fake lazy-imports that I am referring to. https://github.com/PolymerElements/polymer-starter-kit/blob/2.0-preview/src/my-app.html#L25-L28

They aren't properly inside the dom-module and they aren't actually used by anything in the app.

2017-06-14 21:22 UTC, arthurevans commented
Ah, right. I was looking in master. Yeah, agree they shouldn't be there if they don't do anything.

2017-06-14 21:49 UTC, rictic commented
@arthurevans You're 100% right. We need to document lazy-imports, and I think right now is a good time to do it. I wrote up https://github.com/Polymer/lazy-imports/pull/31 as a first step

2017-06-15 11:00 UTC, abdonrd commented
@arthurevans @stramel @rictic thanks for the feedback!

About the fake `lazy-imports`... I think @justinfagnani had added it only to clean Polymer Linter output.

2017-06-15 16:59 UTC, rictic commented
The lazy-imports repo has now been documented.

2017-07-04 05:16 UTC, stramel commented
Just doing a quick profile on use of `importHref` vs `__importLazyGroup`.

Used PSK `2.0-preview` and `ms/2.0-lazy-imports` branches
Ran DevTools JavaScript Profiler.
Cleared out all application data before each run.
Loaded the main page, started profiler.
Loaded non-loaded pages and attempted re-loading previously loaded imports multiple times.

|Method                      |1   |2    |3  |4   |5  |AVG|
|:----------------------------|:--:|:---:|:--:|:---:|:--:|:----:|
|`importHref`               |5.9|3.6|5.1|4.6|4.2|4.68|
|`__importLazyGroup`|6.1|2.8|4.9|4.4|4.2|4.48|

Any help with how to better profile will be greatly appreciated. I haven't really done it before in case you couldn't tell :sweat_smile:

2017-07-05 18:46 UTC, stramel commented
I setup a rough repository for profiling a different way. https://github.com/stramel/profile-lazy-imports

Both averaged around .5 -.7 for importing 3 different assets. Lazy-imports added ~600 bytes minified from what I could tell. Again, super unofficial lol

2017-07-26 01:00 UTC, arthurevans commented on src/my-app.html
> +            if (results.failed.length > 0 || results.loaded.length < 1)
It looks like we're adding a new dependency on `Promise` here in order to add lazy imports. Doesn't that mean that we need to add a `Promise` polyfill to PSK to maintain compatibility?

2017-07-26 04:17 UTC, stramel commented on src/my-app.html
> +            if (results.failed.length > 0 || results.loaded.length < 1)
Good call @arthurevans! :+1: I put out a PR with a note on the readme and added `promise-polyfill` as a devDependency.

2017-09-12 19:19 UTC, FluorescentHallucinogen commented
Any progress?

2017-09-12 19:24 UTC, stramel commented
@FluorescentHallucinogen Waiting for approval on the pending PRs currently.

2017-10-31 20:42 UTC, stramel commented
The PRs for `lazy-imports` functionality have been merged. Tasks still outstanding:

- Tag v2.1.0 and v3.0.0 on `lazy-imports`
- Update the docs PR to reflect the v3.0.0 syntax
- Update this PR to reflect the v3.0.0 syntax
- Docs around tooling with `lazy-imports`?
- Profiling `lazy-imports`?

2018-01-15 19:11 UTC, stramel commented
@justinfagnani All changes to `lazy-imports` have been updated and tagged. Is there anything in here you would like to see changed? I would really like to get this merged before work on P3 gets started.

2018-01-16 19:14 UTC, keanulee commented
Given that we are moving to JS modules with Polymer 3 instead of HTML imports, lazy-imports doesn't seem like a worthwhile move. I'll leave it up to other maintainers, but I'm inclined to close this PR.

2018-01-16 19:20 UTC, stramel commented
@keanulee I figured it would be worth adding for the Polymer 2.0 version as the way to handle lazy imports. Moving to Polymer 3, I agree that `lazy-imports` is no longer necessary. Although, I don't suspect everyone will instantly shift to using Polymer 3 in the enterprise world.

2018-01-16 20:17 UTC, FluorescentHallucinogen commented
Is `lazy-imports` production-ready? If yes, we should add it to PSK and it should be last Polymer 2.x PSK release before Polymer 3.0 PSK release.

2018-01-17 06:29 UTC, andrewspy commented
I have been using `lazy-imports` for Polymer 2.0 for a while now, and I do think it should be added to the last Polymer 2.x PSK release as there are many Polymer 2.x in production now, and it may take a while for Polymer 3.x to gain traction.

2018-01-17 13:18 UTC, FluorescentHallucinogen commented
Are there any production projects that use `lazy-imports`?

BTW, what about adding `lazy-imports` to https://github.com/Polymer/shop and https://github.com/Polymer/news too?

2018-01-17 13:40 UTC, abdonrd requested changes

2018-01-17 13:40 UTC, abdonrd commented on src/my-app.html
> +     */
The annotations of this PR are no longer necessary. Please, delete them.

2018-01-17 13:40 UTC, abdonrd commented
@keanulee @justinfagnani @stramel With this PR, we drop the performance Lighthouse score from 95 to 90.

#### `#master` branch
<img width="1122" alt="screen shot 2018-01-17 at 14 36 17" src="https://user-images.githubusercontent.com/1007051/35045355-e11e6a54-fb93-11e7-9d20-edc63d9aee1b.png">

#### `#master` branch + lazy-imports PR
<img width="1124" alt="screen shot 2018-01-17 at 14 36 41" src="https://user-images.githubusercontent.com/1007051/35045359-e3b65394-fb93-11e7-8a0b-2b66b28c407a.png">

If this can not be improved, I am inclined not to merge it.

2018-01-17 15:49 UTC, stramel commented
We have been running `lazy-imports` at the company I work at for a while. We have launched numerous production apps that currently use `lazy-imports`. I would consider it "production-ready". 

As for performance, I did observe the same thing as @abdonrd when running lighthouse on the PSK. However, just testing manually, I have never seen much difference performance-wise between `lazy-imports` and using `importHref`. The production apps that we have at one point when I released them were getting mid to upper 90s on lighthouse. (Not sure where they are now)

@FluorescentHallucinogen I had planned on trying to get this PR through before attempting to get shop and news to use `lazy-imports`.

2018-02-20 15:51 UTC, stramel commented
@justinfagnani I will take a look soon hopefully.

2018-03-07 23:28 UTC, stramel commented
Here are the results that I found. Please let me know if I can improve something, still new to using Performance tab and profiling in general. 

https://gist.github.com/stramel/82509631e3e187760d4eb916f1ec787a

2018-03-09 19:00 UTC, stramel commented
After some further discussion over on the lazy-imports PR, I believe we came to the conclusion to not use `async` for dynamically added imports. 

@justinfagnani Seeing as `async` is the primary difference in performance here, is there anything else that is holding this PR up?

2018-04-08 06:10 UTC, stramel commented
@justinfagnani Ping

2018-06-19 07:45 UTC, abdonrd commented
@justinfagnani old PR; closing? merging? ...?

2018-06-19 07:57 UTC, stramel commented
Man, I wish we could have got this stuff in for 2.0

2018-12-03 06:07 UTC, closed without merging